# Generated by Django 4.0 on 2022-11-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_permissions_alter_user_managers_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permission',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'accounts'), (1, 'hr'), (2, 'sales'), (3, 'purchase'), (4, 'reports')], null=True),
        ),
    ]
