# Generated by Django 4.0 on 2022-11-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_permissions_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.Permission'),
        ),
    ]
