# Generated by Django 4.0 on 2022-11-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_user_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='permission',
        ),
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sales',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
